version: "3.8"

services:
  neo4j:
    restart: always
    image: neo4j:enterprise
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP interface
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_logs_debug_level=INFO
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  rabbitmq:
    restart: always
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbitmq_lib:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
  trello_extension:
    image: node:alpine
    working_dir: /usr/src/app
    ports:
      - "3001:8080"
    volumes:
      - ./codebase/trello-powerup-html:/usr/src/app:ro
    command: npx http-server -p 8080 # Serve using http-server
  backend_api_service:
    restart: always
    depends_on:
      - rabbitmq
      - ai_service
      - neo4j
    build:
      context: ./codebase/backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5500:5500

  ai_service:
    restart: always
    depends_on:
      - neo4j
      - rabbitmq
    build:
      context: ./codebase/ai_service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 6500:6500

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  rabbitmq_log:
  rabbitmq_lib:
