version: "3.8"

services:
  neo4j:
    image: neo4j:enterprise # Replace with the desired Neo4j version
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP interface
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password # Set your username/password
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_logs_debug_level=INFO
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
